### ISSUE TITLE
Add MQTTSender

### ISSUE THREAD

**Issue by patcon** [WhisperSystems/PushServer#2]
I'm interested in sorting out what this would require, as I'm interested in [MQTT](http://www.hivemq.com/mqtt-essentials-part-3-client-broker-connection-establishment/) as an alternative for a few other non-OWS projects I'm interested in.

I'd plan to create another `mqtt-sender-async` library analogous to [`gcm-sender-async`](https://github.com/WhisperSystems/gcm-sender-async/tree/master/src/main/java/org/whispersystems/gcm/server).

I'll keep this updated. No action required from anyone else.

**Comment by moxie0** [comment]
Feel free to do that in your own fork, but I only want to keep issues open here that are relevant to this piece, and I will never support MQTT.

**Comment by patcon** [comment]
Cool. Fair enough. Thanks man

**Comment by patcon** [comment]
Wait wait, I just caught the last bit about never.

I don't suppose you've summarized any feelings somewhere, so I could understand? I don't really care to work on this specifically right now if you guys aren't interested, but I'd be appreciative if you could share reasons to avoid it.

**Comment by patcon** [comment]
OK, presumably this is it:

> To do it correctly
on mobile data networks, as Google and Apple have, you'd need to work
with every mobile carrier you anticipate the software connecting through
(basically every mobile carrier in the world) in order to receive the
correct carrier assistance.

https://lists.riseup.net/www/arc/whispersystems/2013-09/msg00016.html

For your consideration, I know at least two groups who are working to start or have already created their own MVNO carriers to work out the need for traffic shaping of channels like this. If I'm reading you correctly, would be great if you'd be willing to reconsider if someone were to approach you with partnership in mind for this use-case :)

**Comment by moxie0** [comment]
We're using websockets for that, and while it will always work poorly for people who don't wish to participate in a push network, it's a pretty small demographic. I prefer websockets to mqtt, but in either case, neither of them belong in this service.
