### ISSUE TITLE
Cant execute compiled jar file.

### ISSUE THREAD

**Issue by tauke1** [WhisperSystems/PushServer#5]
After mvn install, i've tried to execute compiled file like a "java -jar target/Push-Server-0.12.0.jar server config/cfg.yml". But the console said "no main manifest attribute, in target/Push-Server-0.12.0.jar".   As i undestood that i should execute pushserver before executing textsecure-server, is it right?

**Comment by moxie0** [comment]
this is not a supported product or a discussion forum
