### ISSUE TITLE
Ubuntu touch push notifications support

### ISSUE THREAD

**Issue by StuntsPT** [WhisperSystems/PushServer#8]
Before anything else, I'm sorry to bump an old issue here, but the original discussion is closed.
I have just read this post:
https://news.ycombinator.com/item?id=13056554

In it it's stated:
"I would consider a clean, well written, and well tested PR for websocket-only support in Signal. I expect it to have high battery consumption and an unreliable user experience, but would be fine with it if it comes with a warning and only runs in the absence of play services."

I think it's quite a fair point.
However, what is it that is preventing #4 from being accepted?
Is it testing? User base? Would it require a big fat warning that it is still an experimental feature? Or would this simply have too much impact on the server side for such a minor number of users to benefit from? What could "we", the Ubuntu touch community do to have the patch reconsidered?

I know this is your project, and how much you have put into it, but is there anything that can be arranged in this regard?

Thank you very much!

**Comment by moxie0** [comment]
We don't have an Ubuntu Touch Signal client.  Maintaining a client for a platform is a lot of work, and in the case of Ubuntu Touch there probably isn't a large enough user base to warrant the time spent.  We'd obviously love to support every platform (Windows Phone, Nokia, BB, Ubuntu, etc...) but we have to make choices given the size of our team.

If someone else wants to maintain an Ubuntu Touch client, they'd have to commit to building something with identical feature parity, a consistent UX, making feature/protocol changes within 3-4 days of the official clients, and maintaining it with that level of dedication and focus for the rest of their life.

Even then, the additional work required on our part of dealing with an additional push service might not be within our means.  There are, sadly, only 24 hrs in the day.  =(

We also don't use GitHub for discussion, so in the future please ask questions on the mailing list or online forums.  Thanks!
